project3:
  name: 'Project 3'
  due_date: "2021-07-22t21:00:00.00-05:00"
  changelog:
    - date: "2021-07-19 -0500"
      description: 'Add try_update tests. Added new files, and updated
      Makefile and data.h'
      more: 'projects/project3/code'
    - date: "2021-07-19 -0500"
      description: 'Add operator TKey. Updated person.h'
      more: 'projects/project3/operator-tkey'
    - date: "2021-07-17 -0500"
      description: "Add missing links for code. No code changes"
    - date: "2021-07-14 -0500"
      description: 'Release initial code'
    - date: "2021-07-13 -0500"
      description: 'Initial Version'
